#!/bin/sh

# the subset font files are c. 1/4 the size of the full files

# bin/python3 -m venv venv
# source venv/bin/activate
# pip3 install fontTools
# pip install brotli

# Basic Latin 0000–007F
# Latin-1 Supplement, 0080–00FF
# Latin Extended-A, 0100–017F
# Latin Extended-B, 0180–024F
# Greek Extended Unicode block U+1F00-1F

# find uses via
#      % glyphhanger ./inuse.txt

# 	"--unicodes=U+A,U+20,U+22,U+28,U+29,U+2C,U+2E,U+2F,U+32,U+33,U+3A,U+41-49,U+4C-4E,U+50,U+52,U+53,U+55-59,U+5B,U+5D,U+5F,U+61-70,U+72-7B,U+7D,U+A0,U+B7,U+3BB,U+3C4,U+20D7,U+2474,U+249C,U+24AD,U+24B8,U+24B9,U+24BC,U+24BE,U+24C1,U+2780-2784,U+278A-278E,U+28B1,U+FE5F,U+1F130,U+1F135,U+1F144,U+1F146",
#   "--unicodes=U+0000-024F,U+03FD,U+03BB,U+3C4,U+1F00-1FFF,U+20D7,U+2474,U+249C,U+24AD,U+24B8,U+24B9,U+24BC,U+24BE,U+24C1,U+2780-2784,U+278A-278E,U+28B1,U+FE5F"
# but "unicodes" above is somehow not accurate... and so you should not use '--unicodes' w/ pyftsubset

# --text-file="inuse.txt" will get you where you need to go
# the file is generated by finding unique chars in the author tables and dictionary and then adding "fp-html.txt" for
# things like "Ⓛ"
# see "mps.fontsubsettingcheck.go" which is only executed if you uncomment a line in "main.go"

# ./subset-one-ttf.sh "fira" "${arr[@]}"

# NOTOFONT

fld="noto"
declare -a arr=("NotoSans-Bold"
                 "NotoSans-BoldItalic"
                 "NotoSans-Condensed"
                 "NotoSans-CondensedItalic"
                 "NotoSans-CondensedSemiBold"
                 "NotoSans-ExtraLight"
                 "NotoSans-Italic"
                 "NotoSans-Light"
                 "NotoSans-Regular"
                 "NotoSans-SemiBold"
                 "NotoSans-SemiCondensed"
                 "NotoSans-SemiCondensedItalic"
                 "NotoSans-Thin"
                 "NotoSansMono-SemiCondensed")

./subset-one-ttf.sh "${fld}" "${arr[@]}"

fld="notodisplay"
declare -a arr=("NotoSansDisplay-Bold" "NotoSansDisplay-Italic" "NotoSansDisplay-Thin"
"NotoSansDisplay_Condensed-SemiBold" "NotoSansMono_Condensed-Regular" "NotoSansDisplay-BoldItalic"
"NotoSansDisplay-Regular" "NotoSansDisplay_Condensed-Italic" "NotoSansDisplay_SemiCondensed-Italic"
"NotoSansDisplay-ExtraLight" "NotoSansDisplay-SemiBold" "NotoSansDisplay_Condensed-Regular"
"NotoSansDisplay_SemiCondensed-Regular" "NotoSansMono_Condensed-Regular")

./subset-one-ttf.sh "${fld}" "${arr[@]}"

# ALEGREYA
fld="alegreya"
declare -a arr=("AlegreyaSans-Bold" "AlegreyaSans-BoldItalic" "AlegreyaSans-Italic" "AlegreyaSans-Light" "AlegreyaSans-LightItalic" "AlegreyaSans-Medium"
"AlegreyaSans-MediumItalic" "AlegreyaSans-Regular")

./subset-one-ttf.sh "${fld}" "${arr[@]}"

# BRILLFONT
fld="brill"
declare -a arr=("Brill-Bold" "Brill-BoldItalic" "Brill-Italic" "Brill-Roman")

./subset-one-ttf.sh "${fld}" "${arr[@]}"

# Computer Modern Unicode
fld="cmu-otf"
declare -a arr=("cmunss" "cmunssdc" "cmunsi" "cmunso" "cmunsx" "cmunbtl")
./subset-one-otf.sh "${fld}" "${arr[@]}"

# FIRAFONT
fld="fira-otf"
declare -a arr=("FiraMono-Regular" "FiraSans-Bold" "FiraSans-BoldItalic"
"FiraSans-Italic" "FiraSans-Light" "FiraSans-Regular"
"FiraSans-SemiBold" "FiraSans-Thin" "FiraSansCondensed-Bold"
"FiraSansCondensed-Italic" "FiraSansCondensed-Regular" "FiraMono-Regular")

./subset-one-otf.sh "${fld}" "${arr[@]}"

# GENTIUMPLUS
fld="gentium"
declare -a arr=("GentiumPlusCompact-Bold" "GentiumPlusCompact-BoldItalic" "GentiumPlusCompact-Italic" "GentiumPlusCompact-Regular")

./subset-one-ttf.sh "${fld}" "${arr[@]}"

# INTERFONT
fld="inter-otf"
declare -a arr=("Inter-Bold" "Inter-BoldItalic" "Inter-Italic" "Inter-Light" "Inter-Thin" "Inter-Medium"
"Inter-Regular" "Inter-SemiBold")

./subset-one-otf.sh "${fld}" "${arr[@]}"

# LATO
fld="lato"
declare -a arr=("Lato-Bold" "Lato-BoldItalic" "Lato-Italic" "Lato-Light" "Lato-LightItalic" "Lato-Medium"
"Lato-MediumItalic" "Lato-Regular" "Lato-SemiboldItalic" "Lato-Semibold")

./subset-one-ttf.sh "${fld}" "${arr[@]}"

# MPLUS
fld="mplus1-otf"
declare -a arr=("Mplus1-Bold"
"Mplus1-Light"
"Mplus1-Medium"
"Mplus1-Regular"
"Mplus1-SemiBold"
"Mplus1-Thin"
"Mplus1Code-Regula")

./subset-one-otf.sh "${fld}" "${arr[@]}"

# ROBOTOFONT
fld="roboto"
declare -a arr=("Roboto-Bold" "Roboto-BoldItalic" "Roboto-Italic"
"Roboto-Light" "Roboto-Thin" "Roboto-Medium"
"Roboto-Regular" "Roboto_Condensed-Bold"
"Roboto_Condensed-Italic" "Roboto_Condensed-Regular" "RobotoMono-Regular"
"Roboto-SemiBold" "Roboto_SemiCondensed-Italic" "Roboto_SemiCondensed-Regular")

./subset-one-ttf.sh "${fld}" "${arr[@]}"

# SOURCEFONT
fld="source"
declare -a arr=("SourceSans3-Bold"
                 "SourceSans3-BoldItalic"
                 "SourceSans3-ExtraLight"
                 "SourceSans3-Italic"
                 "SourceSans3-Light"
                 "SourceSans3-Regular"
                 "SourceSans3-Medium"
                 "SourceCodePro-VariableFont_wght")

./subset-one-ttf.sh "${fld}" "${arr[@]}"

# UBUNTU
fld="ubuntu"
declare -a arr=("UbuntuSans-Bold" "UbuntuSans-BoldItalic" "UbuntuSans-Italic" "UbuntuSans-Light"
"UbuntuSans-LightItalic" "UbuntuSans-Medium" "UbuntuSans-MediumItalic" "UbuntuSans-Regular" "UbuntuMono-Regular"
"UbuntuSans_Condensed-Bold" "UbuntuSans_Condensed-Italic" "UbuntuSans_Condensed-Regular"
"UbuntuSans_SemiCondensed-Regular" "UbuntuSans_SemiCondensed-Italic"
)

./subset-one-ttf.sh "${fld}" "${arr[@]}"


i="iosevka-regular"
pyftsubset ./in/${i}.woff2 \
   --text-file="inuse.txt" \
   --output-file=./out/${i}Subset.woff2 \
   --layout-features='*' \
   --glyph-names \
   --hinting-tables= \
   --recommended-glyphs \
   --ignore-missing-unicodes \
   --ignore-missing-glyphs

i="Iosevka-Regular"
pyftsubset ./in/${i}.ttf \
   --text-file="inuse.txt" \
   --output-file=./out/${i}Subset.ttf \
   --layout-features='*' \
   --glyph-names \
   --hinting-tables= \
   --recommended-glyphs \
   --ignore-missing-unicodes \
   --ignore-missing-glyphs

#declare -a arr=("alegreya" "brill" "fira" "gentium" "inter" "lato" "noto" "plex" "roboto" "source" "ubuntu")
#for i in "${arr[@]}"
#do
#  cp ./out/${i}/*ttf ..HipparchiaGoServer/web/emb/ttf/${i}
#done